<a href="https://colab.research.google.com/github/jjroma25/PRUEVA1/blob/main/Matrices_HomogeneasJOHAOG2_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Matrices Homogeneas en un espacio tridimensional**

**Docente:** PhD Jorge Rudas

**Diseño de prototipos - 2025 I**

**INFOTEP**

In [ ]:
import numpy as np
from sympy import*
init_printing()

### Declaración de variables simbolicas

In [210]:
## Variables Simbolicas
theta = symbols("theta",  real=True)
phi = symbols("phi",  real=True)
psi = symbols("psi",  real=True)
t1_x = symbols("t1_x", real=True)
t1_y = symbols("t1_y", real=True)
t1_z = symbols("t1_z", real=True)
t2_x = symbols("t2_x", real=True)
t2_y = symbols("t2_y", real=True)
t2_z = symbols("t2_z", real=True)

### Rotacion eje x

In [220]:
H_T2 = Matrix([
    [1, 0, 0, t2_x],[0, 1, 0, t2_y],[0, 0, 1, t2_z],[0, 0, 0, 1]])
H_T2

⎡1  0  0  t₂ ₓ ⎤
⎢              ⎥
⎢0  1  0  t_2_y⎥
⎢              ⎥
⎢0  0  1  t_2_z⎥
⎢              ⎥
⎣0  0  0    1  ⎦

In [215]:
H_T1 = Matrix([
    [1, 0, 0, t1_x],[0, 1, 0, t1_y],[0, 0, 1, t1_z],[0, 0, 0, 1]])
H_T1

⎡1  0  0  t₁ ₓ ⎤
⎢              ⎥
⎢0  1  0  t_1_y⎥
⎢              ⎥
⎢0  0  1  t_1_z⎥
⎢              ⎥
⎣0  0  0    1  ⎦

In [216]:
H=H_T1@H_x
H

⎡1    0        0     t₁ ₓ ⎤
⎢                         ⎥
⎢0  cos(φ)  -sin(φ)  t_1_y⎥
⎢                         ⎥
⎢0  sin(φ)  cos(φ)   t_1_z⎥
⎢                         ⎥
⎣0    0        0       1  ⎦

In [217]:
H=H_x@H_T1
H

⎡1    0        0                t₁ ₓ            ⎤
⎢                                               ⎥
⎢0  cos(φ)  -sin(φ)  t_1_y⋅cos(φ) - t_1_z⋅sin(φ)⎥
⎢                                               ⎥
⎢0  sin(φ)  cos(φ)   t_1_y⋅sin(φ) + t_1_z⋅cos(φ)⎥
⎢                                               ⎥
⎣0    0        0                  1             ⎦

In [ ]:
H_x = Matrix([[1, 0, 0, 0], [0, cos(phi), -sin(phi), 0], [0, sin(phi), cos(phi), 0], [0, 0, 0, 1]])
H_x

⎡1    0        0     0⎤
⎢                     ⎥
⎢0  cos(φ)  -sin(φ)  0⎥
⎢                     ⎥
⎢0  sin(φ)  cos(φ)   0⎥
⎢                     ⎥
⎣0    0        0     1⎦

### Rotacion eje y

In [218]:
H=H_T1@H_y
H

⎡cos(θ)   0  sin(θ)  t₁ ₓ ⎤
⎢                         ⎥
⎢   0     1    0     t_1_y⎥
⎢                         ⎥
⎢-sin(θ)  0  cos(θ)  t_1_z⎥
⎢                         ⎥
⎣   0     0    0       1  ⎦

In [219]:
H=H_y@H_T1
H

⎡cos(θ)   0  sin(θ)  t₁ ₓ⋅cos(θ) + t_1_z⋅sin(θ) ⎤
⎢                                               ⎥
⎢   0     1    0                t_1_y           ⎥
⎢                                               ⎥
⎢-sin(θ)  0  cos(θ)  -t₁ ₓ⋅sin(θ) + t_1_z⋅cos(θ)⎥
⎢                                               ⎥
⎣   0     0    0                  1             ⎦

In [221]:
H=H_y@H_T2
H

⎡cos(θ)   0  sin(θ)  t₂ ₓ⋅cos(θ) + t_2_z⋅sin(θ) ⎤
⎢                                               ⎥
⎢   0     1    0                t_2_y           ⎥
⎢                                               ⎥
⎢-sin(θ)  0  cos(θ)  -t₂ ₓ⋅sin(θ) + t_2_z⋅cos(θ)⎥
⎢                                               ⎥
⎣   0     0    0                  1             ⎦

In [226]:
H=H_T2@H_y
H

⎡cos(θ)   0  sin(θ)  t₂ ₓ ⎤
⎢                         ⎥
⎢   0     1    0     t_2_y⎥
⎢                         ⎥
⎢-sin(θ)  0  cos(θ)  t_2_z⎥
⎢                         ⎥
⎣   0     0    0       1  ⎦

In [ ]:
H_y = Matrix([[cos(theta), 0, sin(theta), 0], [0, 1, 0, 0], [-sin(theta), 0, cos(theta), 0], [0, 0, 0, 1]])
H_y


⎡cos(θ)   0  sin(θ)  0⎤
⎢                     ⎥
⎢   0     1    0     0⎥
⎢                     ⎥
⎢-sin(θ)  0  cos(θ)  0⎥
⎢                     ⎥
⎣   0     0    0     1⎦

### Rotacion eje z

In [ ]:
H_z = Matrix([[cos(psi), -sin(psi), 0, 0], [sin(psi), cos(psi), 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
H_z

⎡cos(ψ)  -sin(ψ)  0  0⎤
⎢                     ⎥
⎢sin(ψ)  cos(ψ)   0  0⎥
⎢                     ⎥
⎢  0        0     1  0⎥
⎢                     ⎥
⎣  0        0     0  1⎦

### Composicion de Matrices Homogeneas

Probando la conmutatividad de las matrices homogeneas

In [ ]:
H = H_z@H_y@H_x
H

⎡cos(ψ)⋅cos(θ)  sin(φ)⋅sin(θ)⋅cos(ψ) - sin(ψ)⋅cos(φ)  sin(φ)⋅sin(ψ) + sin(θ)⋅cos(φ)⋅cos(ψ)   0⎤
⎢                                                                                             ⎥
⎢sin(ψ)⋅cos(θ)  sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)  0⎥
⎢                                                                                             ⎥
⎢   -sin(θ)                sin(φ)⋅cos(θ)                          cos(φ)⋅cos(θ)              0⎥
⎢                                                                                             ⎥
⎣      0                         0                                      0                    1⎦

In [ ]:
H=H_t@H_y
H

⎡cos(θ)   0  sin(θ)  t₀⎤
⎢                      ⎥
⎢   0     1    0     t₁⎥
⎢                      ⎥
⎢-sin(θ)  0  cos(θ)  t₂⎥
⎢                      ⎥
⎣   0     0    0     1 ⎦

In [ ]:
H = H_z@H_y@H_x
H

⎡cos(ψ)⋅cos(θ)  sin(φ)⋅sin(θ)⋅cos(ψ) - sin(ψ)⋅cos(φ)  sin(φ)⋅sin(ψ) + sin(θ)⋅cos(φ)⋅cos(ψ)   0⎤
⎢                                                                                             ⎥
⎢sin(ψ)⋅cos(θ)  sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)  0⎥
⎢                                                                                             ⎥
⎢   -sin(θ)                sin(φ)⋅cos(θ)                          cos(φ)⋅cos(θ)              0⎥
⎢                                                                                             ⎥
⎣      0                         0                                      0                    1⎦

In [ ]:
H = H_x@H_y@H_z
H

⎡           cos(ψ)⋅cos(θ)                         -sin(ψ)⋅cos(θ)                  sin(θ)      0⎤
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(θ)⋅cos(ψ) + sin(ψ)⋅cos(φ)  -sin(φ)⋅sin(ψ)⋅sin(θ) + cos(φ)⋅cos(ψ)  -sin(φ)⋅cos(θ)  0⎥
⎢                                                                                              ⎥
⎢sin(φ)⋅sin(ψ) - sin(θ)⋅cos(φ)⋅cos(ψ)  sin(φ)⋅cos(ψ) + sin(ψ)⋅sin(θ)⋅cos(φ)   cos(φ)⋅cos(θ)   0⎥
⎢                                                                                              ⎥
⎣                 0                                      0                          0         1⎦

# **Experimento 1**
#### Comprobar que una secuencia de rotaciones produce el mismo resultado que una composición de matrices homogeneas

In [ ]:
P0 = np.array([1, 1, 0])

1. Probando solo con matrices de rotación en 3D

In [ ]:
#Matriz de rotacion 3D sobre el eje x
R_x = Matrix([[1, 0, 0], [0, cos(theta), -sin(theta)], [0, sin(theta), cos(theta)]])
R_x

⎡1    0        0   ⎤
⎢                  ⎥
⎢0  cos(θ)  -sin(θ)⎥
⎢                  ⎥
⎣0  sin(θ)  cos(θ) ⎦

In [ ]:
#Matriz de rotacion 3D sobre el eje y
R_y = Matrix([[cos(theta), 0, sin(theta)], [0, 1, 0], [-sin(theta), 0, cos(theta)]])
R_y

⎡cos(θ)   0  sin(θ)⎤
⎢                  ⎥
⎢   0     1    0   ⎥
⎢                  ⎥
⎣-sin(θ)  0  cos(θ)⎦

In [ ]:
theta_val = np.pi/9 # 20 grados en radianes
R_x_p0 = np.array(R_x.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
R_y_p0 = np.array(R_y.subs({theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Ry

P0_rotado_x = np.dot(R_x_p0, P0) #Producto punto entre la matrix de rotación y el vector de posición del punto
P0_rotado_y = np.dot(R_y_p0, P0_rotado_x) #Producto punto entre la matrix de rotación y el vector de posición del punto

print(P0_rotado_y)

[ 1.0566704   0.93969262 -0.02062634]


2. Ahora probamos con la composición de matrices homogeneas

In [ ]:
#Se convierte el punto 3D a un punto de coordenadas homogeneas

P0_homogeneo = np.append(P0, 1)
P0_homogeneo = np.reshape(P0_homogeneo, (4, 1))
print(P0)
print(P0_homogeneo)

[1 1 0]
[[1]
 [1]
 [0]
 [1]]


In [ ]:
#Se realiza la composición de las matrices homogeneas para x y y
Hxy = H_y@H_x
Hxy

⎡cos(θ)   sin(φ)⋅sin(θ)  sin(θ)⋅cos(φ)  0⎤
⎢                                        ⎥
⎢   0        cos(φ)         -sin(φ)     0⎥
⎢                                        ⎥
⎢-sin(θ)  sin(φ)⋅cos(θ)  cos(φ)⋅cos(θ)  0⎥
⎢                                        ⎥
⎣   0           0              0        1⎦

In [ ]:
theta_val = np.pi/9 # 20 grados en radianes
phi_val = np.pi/9 # 20 grados en radianes

Hxy_p0 = np.array(Hxy.subs({phi: phi_val, theta: theta_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
Hxy_p0

array([[ 0.93969262,  0.11697778,  0.3213938 ,  0.        ],
       [ 0.        ,  0.93969262, -0.34202014,  0.        ],
       [-0.34202014,  0.3213938 ,  0.88302222,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
P0_rotado_Hxy = np.dot(Hxy_p0, P0_homogeneo)
P0_rotado_Hxy

array([[ 1.0566704 ],
       [ 0.93969262],
       [-0.02062634],
       [ 1.        ]])

# **Actividad**

* Calcule las siguientes matrices homogeneas

In [ ]:
from IPython.display import Image

Image(url='1.png')

## Donde:

In [ ]:
Image(url='2.png')

# **Resultados aquí debajo**

In [ ]:
H = H_z@H_y@H_x
theta_val = np.pi*56/180 # 20 grados en radianes
phi_val = np.pi*2/180 # 20 grados en radianes
psi_val = np.pi*53/180

Hzyx = np.array(H.subs({phi: phi_val, theta: theta_val, psi: psi_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
Hzyx

array([[ 0.33653069, -0.78073669,  0.52649531,  0.        ],
       [ 0.44659131,  0.62455533,  0.64069247,  0.        ],
       [-0.82903757,  0.01951555,  0.55885226,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
np.dot(Hzyx,  P0_homogeneo)

array([[-0.444206  ],
       [ 1.07114664],
       [-0.80952202],
       [ 1.        ]])

In [ ]:
H = H_y@H_x@H_y
theta_val = np.pi*56/180 # 20 grados en radianes
phi_val = np.pi*2/180 # 20 grados en radianes
psi_val = np.pi*53/180

HYXY = np.array(H.subs({phi: phi_val, theta: theta_val, psi: psi_val})).astype(np.float64) #Se convierte theta simbolico a un valor concreto Rx
HYXY

array([[-0.37418791,  0.02893299,  0.92690145,  0.        ],
       [ 0.02893299,  0.99939083, -0.01951555,  0.        ],
       [-0.92690145,  0.01951555, -0.37479708,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
np.dot(HYXY,  P0_homogeneo)

array([[-0.34525491],
       [ 1.02832382],
       [-0.9073859 ],
       [ 1.        ]])

# ***Solucion de taller***

In [224]:
H = H_T1@H_y@H_x@H_T2@H_y #Punto 2 TALLER
H

t1_x_val = 3
t1_y_val = 0
t1_z_val = 0
t2_x_val = 1
t2_y_val = 1
t2_z_val = 0
theta_val = np.pi*6/180
theta_val2 = np.pi*-6/180
phi_val = np.pi*2/180

HT1YXT2Y = np.array(H.subs({t1_x: t1_x_val, t1_y: t1_y_val, t1_z: t1_z_val,t2_x: t2_x_val, t2_y: t2_y_val, t2_z: t2_z_val, theta: theta_val,theta: theta_val2, phi: phi_val})).astype(np.float64)

print("Matriz H con los valores:")
print(HT1YXT2Y)



Matriz H con los valores:
[[ 9.78154257e-01 -3.64799076e-03 -2.07848364e-01  3.99087390e+00]
 [-3.64799076e-03  9.99390827e-01 -3.47083136e-02  9.99390827e-01]
 [ 2.07848364e-01  3.47083136e-02  9.77545084e-01  1.39236777e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [225]:
np.dot(HT1YXT2Y,  P0_homogeneo)

array([[4.96538017],
       [1.99513366],
       [0.38179345],
       [1.        ]])